//base de donnee locale

export const location = { location: "Tunis" };
export const work = { work: "home" };
export const locations = [
  "Tunis",
  "Ariana",
  "Béja",
  "Ben Arous",
  "Bizerte",
  "Gabès",
  "Gafsa",
  "Jendouba",
  "Kairouan",
  "Kasserine",
  "Kébili",
  "Kef",
  "Mahdia",
  "Mannouba",
  "Médenine",
  "Monastir",
  "Nabeul",
  "Sfax",
  "Sidi Bouzid",
  "Siliana",
  "Sousse",
  "Tataouine",
  "Touzer",
  "Zaghouan",
];
export const job=[
  'Home',
  'électricien',
  'plombier',
  'Femme de menage',
  'baby sitter',
  'menuisier'
];
export const data = [
  {
    id: 0,
    name: "ela",
    famillyName: "attia",
    rating: 4,
    work: "baby sitter",
    location: "Tunis",
    phoneNumber: "28285497",
    user: "elal123",
    password: "123456",
    image: require("./images/babySitter.png"),
  },
  {
    id: 1,
    name: "amal",
    famillyName: "ayari",
    rating: 5,
    work: "baby sitter",
    location: "Tunis",
    phoneNumber: "98284497",
    user: "amal123",
    password: "123456",
    image: require("./images/babySitter.png"),
  },
  {
    id: 2,
    name: "samar",
    famillyName: "nheri",
    rating: 3,
    work: "baby sitter",
    location: "Bizerte",
    phoneNumber: "98285467",
    user: "samarl123",
    password: "123456",
    image: require("./images/babySitter.png"),
  },
  {
    id: 3,
    name: "isra",
    famillyName: "saidi",
    rating: 3,
    work: "baby sitter",
    location: "Bizerte",
    phoneNumber: "28285497",
    user: "isral123",
    password: "123456",
    image: require("./images/babySitter.png"),
  },

  {
    id: 4,
    name: "khadija",
    famillyName: "segni",
    rating: 2,
    work: "baby sitter",
    location: "Tunis",
    phoneNumber: "22285497",
    user: "khadijal123",
    password: "123456",
    image: require("./images/babySitter.png"),
  },

  {
    id: 5,
    name: "fatma",
    famillyName: "rais",
    rating: 4,
    work: "baby sitter",
    location: "Bizerte",
    phoneNumber: "93285497",
    user: "fatmal123",
    password: "123456",
    image: require("./images/babySitter.png"),
  },
  {
    id: 6,
    name: "fatma",
    famillyName: "rais",
    rating: 5,
    work: "femme de menage",
    location: "Bizerte",
    phoneNumber: "93285497",
    user: "fatmal123",
    password: "123456",
    image: require("./images/femmeDeMenage.png"),
  },
  {
    id: 7,
    name: "zahra",
    famillyName: "mathlouthy",
    rating: 1,
    work: "femme de mènage",
    location: " Gafsa",
    phoneNumber: "23285497",
    user: "zahral123",
    password: "123456",
    image: require("./images/femmeDeMenage.png"),
  },
  {
    id: 8,
    name: "zayneb",
    famillyName: "hajri",
    rating: 2,
    work: " femme de mènage ",
    location: "Kébili",
    phoneNumber: "50285497",
    user: "zaineb123",
    password: "123456",
    image: require("./images/femmeDeMenage.png"),
  },
  {
    id: 9,
    name: "lamiya",
    famillyName: "hamrouni",
    rating: 4,
    work: " femme de mènage ",
    location: "Sfax",
    phoneNumber: "93288897",
    user: "lamiyal123",
    password: "123456",
    image: require("./images/femmeDeMenage.png"),
  },
  {
    id: 10,
    name: "fayrouz",
    famillyName: "gesmi",
    rating: 5,
    work: "femme de mènage",
    location: "Mahdia",
    phoneNumber: "93285430",
    user: "fayrouzl123",
    password: "123456",
    image: require("./images/femmeDeMenage.png"),
  },
  {
    id: 12,
    name: "amal",
    famillyName: "ben mohamed",
    rating: 2,
    work: "femme de mènage",
    location: "Mannouba",
    phoneNumber: "52722497",
    user: "amal123",
    password: "123456",
    image: require("./images/femmeDeMenage.png"),
  },
  {
    id: 13,
    name: "ahmed",
    famillyName: "labyedh",
    rating: 1,
    work: "plombier",
    location: "Sousse",
    phoneNumber: "25285497",
    user: "ahmedl123",
    password: "123456",
    image: require("./images/plombier.png"),
  },
  {
    id: 14,
    name: "aymen",
    famillyName: "lakhel",
    rating: 4,
    work: "plombier",
    location: "Jendouba",
    phoneNumber: "92225497",
    user: "aymen123",
    password: "123456",
    image: require("./images/plombier.png"),
  },
  {
    id: 15,
    name: "salah",
    famillyName: "dhouibi",
    rating: 5,
    work: "plombier",
    location: "Bizerte",
    phoneNumber: "99285497",
    user: "salah123",
    password: "123456",
    image: require("./images/plombier.png"),
  },
  {
    id: 16,
    name: "mohamed",
    famillyName: "badredine",
    rating: 3,
    work: "plombier",
    location: "Kairouan",
    phoneNumber: "52285497",
    user: "mohamed123",
    password: "123456",
    image: require("./images/plombier.png"),
  },
  {
    id: 17,
    name: "ramzi",
    famillyName: "outay",
    rating: 2,
    work: "plombier",
    location: "Nabeul",
    phoneNumber: "50328549",
    user: "ramzi123",
    password: "123456",
    image: require("./images/plombier.png"),
  },
  {
    id: 18,
    name: "mondher",
    famillyName: "jouini",
    rating: 1,
    work: "menuisier",
    location: "Touzer",
    phoneNumber: "55289497",
    user: "amineal123",
    password: "123456",
    image: require("./images/menuisier.png"),
  },
  {
    id: 19,
    name: "kamel",
    famillyName: "ben sayar",
    rating: 2,
    work: "menuisier",
    location: "Siliana",
    phoneNumber: "41285497",
    user: "amineal123",
    password: "123456",
    image: require("./images/menuisier.png"),
  },
  {
    id: 20,
    name: "mohsen",
    famillyName: "siidy",
    rating: 3,
    work: "menuisier",
    location: "Médenine",
    phoneNumber: "22478497",
    user: "amineal123",
    password: "123456",
    image: require("./images/menuisier.png"),
  },
  {
    id: 21,
    name: "sofyen",
    famillyName: "benzineb",
    rating: 4,
    work: "menuisier",
    location: "Béja",
    phoneNumber: "23655497",
    user: "amineal123",
    password: "123456",
    image: require("./images/menuisier.png"),
  },
  {
    id: 22,
    name: "amer",
    famillyName: "danden",
    rating: 5,
    work: "menuisier",
    location: "Ariana",
    phoneNumber: "53285497",
    user: "amineal123",
    password: "123456",
    image: require("./images/menuisier.png"),
  },
  {
    id: 23,
    name: "amer",
    famillyName: "danden",
    rating: 5,
    work: "électricien",
    location: "Ariana",
    phoneNumber: "53285497",
    user: "amineal123",
    password: "123456",
    image: require("./images/électricien.png"),
  },
 
  {
    id: 24,
    name: "sami",
    famillyName: "danden",
    rating: 3,
    work: "électricien",
    location: "Kairouan.",
    phoneNumber: "41585497",
    user: "sami123",
    password: "123456",
    image: require("./images/électricien.png"),
  },
  {
    id: 25,
    name: "mostpha",
    famillyName: "faouel",
    rating: 1,
    work: "électricien",
    location: "Gabès",
    phoneNumber: "53405497",
    user: "mostpha123",
    password: "123456",
    image: require("./images/électricien.png"),
  },
  {
    id: 26,
    name: "melek",
    famillyName: "jamli",
    rating: 2,
    work: "électricien",
    location: "Ben Arous",
    phoneNumber: "26285497",
    user: "melek123",
    password: "123456",
    image: require("./images/électricien.png"),
  },
  {
    id: 27,
    name: "abd slem",
    famillyName: "jriri",
    rating: 3,
    work: "électricien",
    location: "Sfax",
    phoneNumber: "53285497",
    user: "abd sleml123",
    password: "123456",
    image: require("./images/électricien.png"),
  },
  {
    id: 28,
    name: "mohamed",
    famillyName: "jbeli",
    rating: 5,
    work: "électricien",
    location: "Médenine",
    phoneNumber: "28569497",
    user: "mohamed123",
    password: "123456",
    image: require("./images/électricien.png"),
  },
 
  
];

export default data;
