export const locations = [
    'Please select your city',
    'Tunis',
    'Ariana',
    'Béja',
    'Ben Arous',
    'Bizerte',
    'Gabès',
    'Gafsa',
    'Jendouba',
    'Kairouan',
    'Kasserine',
    'Kébili',
    'Kef',
    'Mahdia',
    'Mannouba',
    'Médenine',
    'Monastir',
    'Nabeul',
    'Sfax',
    'Sidi Bouzid',
    'Siliana',
    'Sousse',
    'Tataouine',
    'Touzer',
    'Zaghouan',
  ];
  
  export const jobs = [
    'Please select your job',
    'électricien',
    'plombier',
    'Femme de menage',
    'baby sitter',
    'menuisier',
  ];